# 3 线性代数
## 3.1 标量

标量：只有一个元素的张量表示

In [1]:
import torch
x = torch.tensor(3.0)
y = torch.tensor(2.0)
x + y, x * y, x / y, x** y

(tensor(5.), tensor(6.), tensor(1.5000), tensor(9.))

## 3.2 向量
向量可视为标量值组成的列表。标量值被称为向量的元素（element）或分量（component）。大量文献认为向量的默认方向为列向量。
$$
\mathbf x=
\begin{bmatrix}
x_1\\ x_2\\...\\ x_n
\end{bmatrix}
$$

In [2]:
x = torch.arange(4)
x

tensor([0, 1, 2, 3])

In [3]:
# 可以调用python内置的len()函数来访问张量的长度。也提供.shape属性访问向量的长度
len(x), x.shape

(4, torch.Size([4]))

## 3.3 矩阵

矩阵将向量丛一阶推广到二阶。表示为具有两个轴的张量。

In [4]:
A = torch.arange(20).reshape(5,4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [5]:
# 矩阵的转置
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

## 3.4 张量

张量描述具有任意数量轴的n维数组的通用方法。

In [31]:
X = torch.arange(24).reshape(2, 3, 4)
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

## 3.5 张量算法的基本性质

按元素的一元运算都不会改变其操作数的形状。给定具有相同形状的任意两个张量，任何按元素的二元运算的结果都不会改变其操作数的形状。

In [7]:
A = torch.arange(20, dtype=torch.float32).reshape(5,4)
B = A.clone()
A, A+B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

两个矩阵的按元素乘法称为Hadamard 积（数学符号$\odot$）

In [8]:
A * B

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

将张量乘以或加上一个标量不会改变张量的形状，其中每个元素都将以标量相加或相乘

In [9]:
a = 2

X = torch.arange(24).reshape(2, 3, 4)
a + X, (a * X).shape

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 torch.Size([2, 3, 4]))

## 3.6 降维

计算元素之和。默认沿着所有的轴降低张量的维度变成一个标量。

In [10]:
x = torch.arange(4, dtype=torch.float32)
x, x.sum()

(tensor([0., 1., 2., 3.]), tensor(6.))

In [13]:
print(A.shape,A.sum())

A_sum_axis0 = A.sum(axis=0)
print(A_sum_axis0, A_sum_axis0.shape)

A_sum_axis1 = A.sum(axis=1)
print(A_sum_axis1, A_sum_axis1.shape)

torch.Size([5, 4]) tensor(190.)
tensor([40., 45., 50., 55.]) torch.Size([4])
tensor([ 6., 22., 38., 54., 70.]) torch.Size([5])


In [17]:
# 求平均值

print(A.mean(), A.sum()/A.numel())

print(A.mean(axis=0), A.sum(axis=0)/A.shape[0])

tensor(9.5000) tensor(9.5000)
tensor([ 8.,  9., 10., 11.]) tensor([ 8.,  9., 10., 11.])


In [21]:
# 非降维求和
sum_A = A.sum(axis = 1, keepdims = True)

sum_A, A/sum_A

(tensor([[ 6.],
         [22.],
         [38.],
         [54.],
         [70.]]),
 tensor([[0.0000, 0.1667, 0.3333, 0.5000],
         [0.1818, 0.2273, 0.2727, 0.3182],
         [0.2105, 0.2368, 0.2632, 0.2895],
         [0.2222, 0.2407, 0.2593, 0.2778],
         [0.2286, 0.2429, 0.2571, 0.2714]]))

In [23]:
# 计算累计总和

A,A.cumsum(axis=0)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  6.,  8., 10.],
         [12., 15., 18., 21.],
         [24., 28., 32., 36.],
         [40., 45., 50., 55.]]))

## 3.7 点积 

给定两个向量$\mathbf{x,y}\in\mathbb R^d$，其点积$\mathbf{x^\top y}$为相同位置的按元素乘积的和：$\mathbf{x^\top y}=\sum_{i=1}^dx_iy_i$

In [25]:
y = torch.ones(4,dtype=torch.float32)

x, y, torch.dot(x, y), torch.sum(x * y)

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.), tensor(6.))

## 3.8 矩阵向量积

使用mv函数计算矩阵-向量积。注意，A的列维数必须与x的维数相同
$$
\mathbf{Ax} = 
\begin{bmatrix}
\mathbf a_1^{\top}\\
\mathbf a_2^{\top}\\
...\\
\mathbf a_m^{\top}
\end{bmatrix}\mathbf x = 
\begin{bmatrix}
\mathbf a_1^{\top}\mathbf x\\
\mathbf a_2^{\top}\mathbf x\\
...\\
\mathbf a_m^{\top}\mathbf x
\end{bmatrix}

$$


In [26]:
A.shape, x.shape, torch.mv(A, x)

(torch.Size([5, 4]), torch.Size([4]), tensor([ 14.,  38.,  62.,  86., 110.]))

## 3.9 矩阵-矩阵乘法
$$
\mathbf{C=AB=
\begin{bmatrix}
\mathbf a_1^\top\\
\mathbf a_2^\top\\
...\\
\mathbf a_n^\top\\
\end{bmatrix}

\begin{bmatrix}
\mathbf {b_1\ b_2\ ...\ b_m}
\end{bmatrix}
}
 $$

In [27]:
B = torch.ones(4,3)
torch.mm(A, B)

tensor([[ 6.,  6.,  6.],
        [22., 22., 22.],
        [38., 38., 38.],
        [54., 54., 54.],
        [70., 70., 70.]])

## 3.10 范数
范数（norm）。表示一个向量有多大。
线性代数中，向量范数是将向量映射到标量的函数f。给定任意向量$\mathbf x$，向量范数要满足一些属性。

性质1：按常数因子$\alpha$，其范数也会按照相同的常数因子的绝对值缩放
$$
f(\alpha \mathbf x)=|\alpha|f(x)
$$
性质2：三角不等式
$$
f(\mathbf{x+y})\le f(x) + f(y)
$$
性质3：范数非负
$$
f(x)\ge 0
$$
性质4：范数最小为0，当且仅当向量由全0组成
$$
\forall i,[\mathbf x]_i=0\Leftrightarrow f(\mathbf x)=0
$$

 L2范数
 $$
||\mathbf x||_2=\sqrt{\sum_{i=1}^nx_i^2}
 $$

In [28]:
u = torch.tensor([3.0,-4.0])
torch.norm(u)

tensor(5.)

L1范数，表示为向量元素的绝对值之和：
$$
||\mathbf x||_1=\sum_{i=1}^n|x_i|
$$

In [29]:
torch.abs(u).sum()

tensor(7.)

Lp范数
$$
||\mathbf x||_p=\bigg(\sum_{i=1}^n|x_i|^p \bigg)^{1/p}
$$

矩阵的Frobrnius范数是矩阵元素平方和的平方根
$$
||X||_F=\sqrt{\sum_{i=1}^m\sum_{j=1}^n x_{ij}^2}
$$

In [30]:
torch.norm(torch.ones((4,9)))

tensor(6.)