# 6 深度学习计算

## 6.1 层和块

单个神经网络：（1）接受一些输入；（2）生成相应的标量输出；（3）具有一组相关参数（parameters）

当考虑具有多个输出的网络时，利用矢量化算法描述整层神经元。（1）接受一组输入；（2）生成相应的输出，（3）由一组可调参数描述。

神经网络块（block）：描述单个层、由多个层组成的组件或整个模型本身。

从编程的角度看，块由类（class）表示。它的任何子类都必须顶一个将输入转换为输出的前向传播函数，并且必须存储任何必须的参数。最后，为了计算梯度，块必须具有反向传播函数。


In [1]:
import torch
from torch import nn
from torch.nn import functional as F
'''
nn.Sequential定义了一种特殊的Module，表示一个块的类，维护了一个由Module组成的有序列表。
net(X)调用模型获得输出，实际上时net.__call__(X)的缩写。该前向传播函数非常简单，将列表中的每个块连接在一起，将每个块的输出作为下一个块的输入
'''

net = nn.Sequential(
    nn.Linear(20,256),
    nn.ReLU(),
    nn.Linear(256,10)
)

X = torch.rand(2,20)
net(X)

tensor([[ 0.0147, -0.1013,  0.0462, -0.0341,  0.0880,  0.0883,  0.1416,  0.1222,
          0.0079,  0.2121],
        [-0.0269, -0.0583,  0.0798, -0.0463,  0.0440,  0.2346,  0.2099,  0.0330,
          0.0123,  0.2409]], grad_fn=<AddmmBackward0>)

#### 自定义块

每个块必须提供的功能：
1. 将输入数据作为其前向传播的参数
2. 通过前向传播函数来生成输出
3. 计算其输出关于输入的梯度，可通过反向传播函数进行访问
4. 存储和访问前向传播计算所需的参数
5. 根据需要初始化模型参数

编写一个自定义多层感知机，具有256个隐藏单元的隐藏层和一个输出层。MLP类继承了表示块的类。我们只需实现构造函数（__init__函数）和前向传播函数。


In [2]:
class MLP(nn.Module):
    # 用模型参数声明层。在此声明两个全连接的层
    def __init__(self, input_dim, out_dim):
        # 调用父类Module的构造函数离开执行必要的初始化
        super().__init__()
        self.hidden = nn.Linear(input_dim, 256) # 隐藏层
        self.out = nn.Linear(256, out_dim) # 输出层
    # 定义模型的前向传播，即如何根据输入X返回所需的输出
    def forward(self, X):
        return F.softmax(self.out(F.relu(self.hidden(X))), dim=1)

net = MLP(20,10)
net(X)

tensor([[0.0949, 0.1217, 0.0999, 0.0670, 0.1072, 0.0875, 0.0942, 0.1016, 0.1274,
         0.0986],
        [0.1012, 0.1185, 0.0890, 0.0645, 0.1074, 0.0939, 0.0968, 0.0896, 0.1345,
         0.1046]], grad_fn=<SoftmaxBackward0>)

块的一个主要有点就是其多功能性。可以子类化块一创建层（如全连接的类）、整个模型（如上面的MLP）或具有中等复杂度的各种组件。

#### 顺序块

Sequential类徐定义两个关键函数：
1. 将块逐个追加到列表中的函数
2. 前向传播函数，用于将输入按追加块的顺序传递给块组成的“链条”

下面的MySequential类提供了与默认Sequential类相同的功能

In [3]:
class MySequential(nn.Module):
    def __init__(self, *args):
        super().__init__()
        for idx, module in enumerate(args):
            # module时Module子类的一个实例
            # _module的类型时OrderedDict
            self._modules[str(idx)] = module

    def forward(self, X):
        # OrderedDict保证按照成员添加的顺序便利他们，主要优势时哎模块的参数初始化过程中，系统知道在_modules字典中查找需要初始化参数的子块。

        for block in self._modules.values():
            X = block(X)
        return X

net = MySequential(nn.Linear(20, 256), nn.ReLU(), nn.Linear(256,10), nn.Softmax(dim=1))
net(X)

tensor([[0.0867, 0.1144, 0.0994, 0.0948, 0.0916, 0.1042, 0.1053, 0.0964, 0.1020,
         0.1052],
        [0.0969, 0.1318, 0.0939, 0.0947, 0.0936, 0.1095, 0.0999, 0.0942, 0.0878,
         0.0976]], grad_fn=<SoftmaxBackward0>)

#### 在前向传播函数中执行代码

并不是所有的架构都是简单的顺序架构。当需要更强的灵活性时，我们需要自定义块。如在前向传播中执行Python控制流和任意的数学运算。

网络中的所有操作都对网络的激活值及网络的参数起作用。然而，有时希望合并既不是上一层的结果也不是可更新参数的项，称之为常数参数（constant parameter）。如

$$
f(\mathbf{x,w})=c\cdot\mathbf{w^\top x}
$$
其中，$\mathbf x$是参数，$\mathbf w$是参数，c是某个在优化过程中没有更新的指定常量

In [4]:
class FixedHiddenMLP(nn.Module):
    def __init__(self, input_dim, out_dim):
        super().__init__()
        # 不计算随机权重的梯度。因此其在训练期间保持不变
        self.rand_weight = torch.rand((256, out_dim), requires_grad=False)
        self.linear = nn.Linear(input_dim, 256)
    
    def forward(self, X):
        X = self.linear(X)
        # 使用创建的常量参数及relu和mm函数, 常量参数不会被反向传播更新
        X = F.relu(torch.mm(X, self.rand_weight)+1)
        # 控制流
        while X.abs().sum() > 1:
            X /= 2
        return X.sum()

net = FixedHiddenMLP(20,10)
net(X)

tensor(0.5493, grad_fn=<SumBackward0>)

In [5]:
net = nn.Sequential(nn.Linear(20, 256), nn.ReLU(), nn.Linear(256,10), nn.Softmax())
net(X)

/home/kazundo/miniconda3/envs/Bio/lib/python3.13/site-packages/torch/nn/modules/module.py:1736: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  return self._call_impl(*args, **kwargs)


tensor([[0.0949, 0.1372, 0.1065, 0.0962, 0.0820, 0.0770, 0.0951, 0.0809, 0.1145,
         0.1157],
        [0.0885, 0.1371, 0.1079, 0.0931, 0.0842, 0.0685, 0.1049, 0.0837, 0.1220,
         0.1102]], grad_fn=<SoftmaxBackward0>)

## 6.2 参数管理

### 参数访问

从已有模型中访问参数。当通过Sequential类定义模型时，可以通过索引来访问模型的任意层。这就像模型是一个列表一样，每层的参数都在其属性中。

In [6]:
# 访问第二个全连接层的参数

net[2].state_dict()

OrderedDict([('weight',
              tensor([[ 0.0425, -0.0177, -0.0394,  ...,  0.0090,  0.0040, -0.0610],
                      [-0.0078,  0.0619,  0.0202,  ..., -0.0273, -0.0621,  0.0487],
                      [-0.0438,  0.0369, -0.0524,  ...,  0.0453, -0.0202,  0.0408],
                      ...,
                      [ 0.0093,  0.0429, -0.0153,  ..., -0.0382, -0.0154,  0.0115],
                      [ 0.0089,  0.0587, -0.0137,  ...,  0.0194,  0.0138, -0.0114],
                      [-0.0411, -0.0171, -0.0309,  ..., -0.0233, -0.0074, -0.0082]])),
             ('bias',
              tensor([ 0.0034,  0.0155, -0.0576, -0.0204,  0.0169,  0.0040,  0.0104, -0.0097,
                       0.0274, -0.0042]))])

### 目标参数

每个参数都表示为参数类的一个实例。对参数执行任何操作都需要访问底层的数值。
参数是复合的对象，包含值，梯度和额外信息。没调用反向传播，所以参数的梯度处于初始状态

In [7]:
print(type(net[2].bias))
print(net[2].bias)
print(net[2].bias.data)

<class 'torch.nn.parameter.Parameter'>
Parameter containing:
tensor([ 0.0034,  0.0155, -0.0576, -0.0204,  0.0169,  0.0040,  0.0104, -0.0097,
         0.0274, -0.0042], requires_grad=True)
tensor([ 0.0034,  0.0155, -0.0576, -0.0204,  0.0169,  0.0040,  0.0104, -0.0097,
         0.0274, -0.0042])


In [8]:
# 一次性访问所有参数

print(*[(name, param.shape) for name, param in net[0].named_parameters()])

print(*[(name, param.shape) for name, param in net.named_parameters()])

('weight', torch.Size([256, 20])) ('bias', torch.Size([256]))
('0.weight', torch.Size([256, 20])) ('0.bias', torch.Size([256])) ('2.weight', torch.Size([10, 256])) ('2.bias', torch.Size([10]))


In [9]:
# 另一种访问方式

net.state_dict()['2.bias'].data

tensor([ 0.0034,  0.0155, -0.0576, -0.0204,  0.0169,  0.0040,  0.0104, -0.0097,
         0.0274, -0.0042])

In [10]:
# 从嵌套块收集参数
def block1():
    return nn.Sequential(nn.Linear(4,8),
                         nn.Linear(8,4),
                         )

def block2():
    net = nn.Sequential()
    for i in range(4):
        net.add_module(f'block{i}',block1())
    return net

rgnet = nn.Sequential(block2(),nn.Linear(4,1))
X = torch.rand((2,4))
print(f'model output:\n{rgnet(X)}')

print(rgnet)

model output:
tensor([[0.0188],
        [0.0187]], grad_fn=<AddmmBackward0>)
Sequential(
  (0): Sequential(
    (block0): Sequential(
      (0): Linear(in_features=4, out_features=8, bias=True)
      (1): Linear(in_features=8, out_features=4, bias=True)
    )
    (block1): Sequential(
      (0): Linear(in_features=4, out_features=8, bias=True)
      (1): Linear(in_features=8, out_features=4, bias=True)
    )
    (block2): Sequential(
      (0): Linear(in_features=4, out_features=8, bias=True)
      (1): Linear(in_features=8, out_features=4, bias=True)
    )
    (block3): Sequential(
      (0): Linear(in_features=4, out_features=8, bias=True)
      (1): Linear(in_features=8, out_features=4, bias=True)
    )
  )
  (1): Linear(in_features=4, out_features=1, bias=True)
)


In [11]:
# 因为层是分层嵌套的，所以可以通过列表索引一样访问。
# 访问第一个主要的块第二个子块的第一层的偏置

print(rgnet[0][1][0].bias.data)

tensor([ 0.3271,  0.2926, -0.3291,  0.0452,  0.2549,  0.3763,  0.4616,  0.1616])


### 参数初始化

首先调用内置的初始化

In [12]:
# 权重初始化为标准差为0.01的高斯随机变量，偏置参数为0

def init_normal(m):
    if type(m) == nn.Linear:
        nn.init.normal_(m.weight, mean=0, std = 0.01)
        nn.init.zeros_(m.bias)
net.apply(init_normal)
net[0].weight.data[0], net[0].bias.data[0]

(tensor([-0.0037,  0.0023, -0.0149, -0.0150, -0.0007,  0.0070, -0.0099,  0.0003,
          0.0036,  0.0009, -0.0003, -0.0008, -0.0163,  0.0007,  0.0055, -0.0102,
         -0.0115, -0.0126,  0.0009, -0.0049]),
 tensor(0.))

In [13]:
# 将所有参数初始化为常数，如1

def init_constant(m):
    if type(m) == nn.Linear:
        nn.init.constant_(m.weight,1)
        nn.init.zeros_(m.bias)
net.apply(init_constant)
net[0].weight.data[0],net[0].bias.data[0]

(tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1.]),
 tensor(0.))

In [14]:
# 还可以对块应用不同的初始化方法，如下面对第一个神经网络层使用Xavier初始化，第三个神经网络层常数初始化
def init_Xavier(m):
    if type(m) == nn.Linear:
        nn.init.xavier_uniform_(m.weight)

net[0].apply(init_Xavier)
net[2].apply(init_constant)

net[0].weight.data[0], net[2].weight.data


(tensor([ 0.1050,  0.0181,  0.0276, -0.0673, -0.1215,  0.0458, -0.0287, -0.1474,
         -0.0319, -0.0852,  0.0664,  0.0531,  0.0904, -0.0719,  0.0401, -0.0686,
         -0.1458,  0.0636, -0.1382,  0.0354]),
 tensor([[1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         ...,
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.]]))

In [15]:
net

Sequential(
  (0): Linear(in_features=20, out_features=256, bias=True)
  (1): ReLU()
  (2): Linear(in_features=256, out_features=10, bias=True)
  (3): Softmax(dim=None)
)

In [16]:
# 自定义初始化

def my_init(m):
    if type(m) == nn.Linear:
        print("init", *[(name,param.shape) for name, param in m.named_parameters()][0])
        nn.init.uniform_(m.weight, -10, 10)
        m.weight.data *= m.weight.data.abs() >= 5
net.apply(my_init)
net[0].weight[:2]

init weight torch.Size([256, 20])
init weight torch.Size([10, 256])


tensor([[-0.0000,  7.7518,  0.0000,  5.8385, -0.0000,  6.1396,  0.0000, -5.3778,
          0.0000, -6.1555, -0.0000, -9.6856, -0.0000,  0.0000, -6.2530,  8.1106,
          9.1399,  6.1854, -0.0000, -0.0000],
        [-0.0000, -5.2049,  5.3870, -9.5657,  8.2809,  0.0000,  0.0000,  5.1157,
         -0.0000, -0.0000, -0.0000, -0.0000,  0.0000,  0.0000, -0.0000,  8.4916,
         -7.5526, -0.0000, -0.0000,  9.0802]], grad_fn=<SliceBackward0>)

In [17]:
# 可以直接设置参数

net[0].weight.data[:] += 1
net[0].weight.data[0, 0] = 42
net[0].weight.data[0]

tensor([42.0000,  8.7518,  1.0000,  6.8385,  1.0000,  7.1396,  1.0000, -4.3778,
         1.0000, -5.1555,  1.0000, -8.6856,  1.0000,  1.0000, -5.2530,  9.1106,
        10.1399,  7.1854,  1.0000,  1.0000])

### 参数绑定

有时希望在多个层间共享参数：可以定义一个稠密层，使用它的参数来设置另一个层的参数

In [18]:
# 给共享层一个名称，以便引用其参数
share = nn.Linear(8, 8)

net = nn.Sequential(nn.Linear(4, 8), nn.ReLU(),
                    share, nn.ReLU(),
                    share, nn.ReLU(),
                    nn.Linear(8,1)
                    )
net(X)

# 检查参数是否相同
print(net[2].weight.data[0] == net[4].weight.data[0])

net[2].weight.data[0, 0] == 100
# 确保其实际上是同一个对象，而非仅具有相同的值， 反向传播时梯度会加在一起
print(net[2].weight.data[0] == net[4].weight.data[0])


tensor([True, True, True, True, True, True, True, True])
tensor([True, True, True, True, True, True, True, True])


## 6.3 延后初始化

深度学习框架在未知网络的输入维度时可通过延后初始化（defers initialization），即直到数据第一次通过模型时才会动态地推断每个层的大小。识别出第一层形状后，就可以推断所有的形状，只有第一层需要延后初始化，后续仍是按顺序初始化。



## 6.4 自定义层

### 不带参数的层

首先构造一个没有任何参数的自定义层。

In [19]:
# 下面的CenteredLayer类从其输入中减去均值，仅需构建类并实现前向传播功能

class CenteredLayer(nn.Module):
    def __int__(self):
        super().__init__()
    
    def forward(self, X):
        return X - X.mean()
    
layer = CenteredLayer()

layer(torch.FloatTensor([1, 2, 3, 4, 5]))


tensor([-2., -1.,  0.,  1.,  2.])

In [20]:
# 合并到复杂的模型中

net = nn.Sequential(nn.Linear(8 ,128), CenteredLayer())

Y = torch.rand((4,8))
net(Y).mean()

tensor(5.5879e-09, grad_fn=<MeanBackward0>)

### 带参数的层

使用内置函数来创建参数，这些函数提供基本的管理功能。如管理访问，初始化、共享、保存和加载模型参数，这么做的好处时不需要为每个自定义层编写自定义的序列化程序。


In [21]:
class MyLinear(nn.Module):
    def __init__(self, in_units, units):
        super().__init__()
        self.weight = nn.Parameter(torch.randn(in_units, units))
        self.bias = nn.Parameter(torch.randn(units,))

    def forward(self, X):
        linear = torch.matmul(X, self.weight.data)
        return F.relu(linear)
    
linear = MyLinear(5, 3)
linear.weight

Parameter containing:
tensor([[ 0.6618, -0.9265,  0.6257],
        [ 0.4766, -2.4799, -1.2596],
        [ 0.0740, -0.6635, -1.5579],
        [ 0.3511,  0.8900,  1.1117],
        [-0.9708,  1.4694, -0.8520]], requires_grad=True)

In [22]:
# 前向传播
linear(torch.rand(2, 5))

tensor([[0.5880, 0.0000, 0.0000],
        [0.1944, 0.0000, 0.0000]])

In [23]:
# 构建模型

net = nn.Sequential(MyLinear(64, 8), MyLinear(8, 1))
net(torch.rand(2, 64))

tensor([[1.2163],
        [5.8639]])

## 6.5 读写文件

### 加载和保存张量
对于单个张量，直接调用load和save 函数分别读写。这两个函数需要提供一个名称，save要求将要保存的变量作为输入


In [24]:
SAVE_PATH = '/home/kazundo/WorkSpace/Methods/bioinfo-dl-tutorial/data/tutorial/'
x = torch.arange(4)
torch.save(x, SAVE_PATH+'x-file')

x2 = torch.load(SAVE_PATH+'x-file', weights_only=True)
x2

tensor([0, 1, 2, 3])

In [25]:
# 可以存储一个张量列表，将其读回内存
y = torch.zeros(4)
torch.save([x,y],SAVE_PATH+'x-files')

x2, y2 = torch.load(SAVE_PATH+'x-files', weights_only=True)
(x2, y2)

(tensor([0, 1, 2, 3]), tensor([0., 0., 0., 0.]))

In [26]:
# 甚至可以写入或读取从字符串映射到张量的字典

mydict = {'x':x, 'y':y}
torch.save(mydict,SAVE_PATH+'mydict')

mydict2 = torch.load(SAVE_PATH+'mydict', weights_only=True)
mydict2

{'x': tensor([0, 1, 2, 3]), 'y': tensor([0., 0., 0., 0.])}

### 加载和保存模型参数

深度学习框架提供了内置函数来保存和加载整个网络。需要注意的是，这将保存模型的参数而不是整个模型。

In [27]:
net = MLP(20,10)
X = torch.rand((2,20))
Y = net(X)
# 存储在一个叫做“mlp.params”
torch.save(net.state_dict(), SAVE_PATH+'mlp.params')

# 实例化原始多层感知机模型的一个备份
clone = MLP(20,10)
clone.load_state_dict(torch.load(SAVE_PATH+'mlp.params', weights_only=True))
clone.eval()

MLP(
  (hidden): Linear(in_features=20, out_features=256, bias=True)
  (out): Linear(in_features=256, out_features=10, bias=True)
)

In [28]:
Y_clone = clone(X)
Y_clone == Y

tensor([[True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True]])

## 5.6 GPU

```sh
!nvidia-smi
```
查看显卡信息
```
Tue Jan 13 14:11:17 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.95.05              Driver Version: 580.95.05      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA A30                     Off |   00000000:21:00.0 Off |                    0 |
| N/A   30C    P0             33W /  165W |      14MiB /  24576MiB |      0%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A         3994727      G   /usr/lib/xorg/Xorg                        4MiB |
+-----------------------------------------------------------------------------------------+
```

PyTorch中，每个数组都有一个设备（device），通常称之为环境（context）。默认情况下所有的变量和计算都分配给CPU。

### 计算设备

可以指定用于存储和计算的设备。PyTorch中，CPU和GPU可以用`torch.device('cpu')`和`torch.device('GPU')`表示。如果有多个GPU，使用`torch.device(f'cuda:{i}')`来表示第i块GPU（i从0）开始。cuda:0等价于cuda

In [2]:
import torch
from torch import nn

print(torch.device('cpu'), torch.device('cuda'), torch.device('cuda:1'))
torch.cuda.device_count()

cpu cuda cuda:1


1

In [3]:
# 定义一个方便的函数，允许在不存在所需所有GPU的情况下允许代码

def try_gpu(i=0):
    if torch.cuda.device_count() >= i+1:
        return torch.device(f'cuda:{i}')
    else:
        return torch.device('cpu')
try_gpu(), try_gpu(2)

(device(type='cuda', index=0), device(type='cpu'))

In [4]:
# 查询张量所在的设备
x = torch.tensor([1, 2, 3])
x.device

device(type='cpu')

需要注意的是，对多个项进行操作，其必须在同一个设备上。
#### 存储在GPU上

在gpu上面创建的张量只消耗这个GPU的显存。


In [6]:
# 在创建张量时指定存储设备
X  = torch.ones(2, 3, device=try_gpu())
X

tensor([[1., 1., 1.],
        [1., 1., 1.]], device='cuda:0')

#### 复制

如果需要计算X + Y，需要将二者移动到同一个设备上

In [8]:
Y = torch.zeros(2, 3, device=try_gpu())
X+Y

tensor([[1., 1., 1.],
        [1., 1., 1.]], device='cuda:0')

#### 旁注
设备之间（CPU、GPU和其他及其）之间传输数据比计算慢得多。使得难以并行化，因为必须等待数据发送或接收完成后才能进行后续操作。

在打印张量或将张量转换为NumPy格式时，若数据不在内存中，则框架会首先将其复制到内存中，导致额外的传输开销。

### 神经网络与GPU
类似的，神经网络模型也可以指定设备。

In [ ]:
net = nn.Sequential(nn.Linear(3, 1))
net = net.to(device=TryGpu())

# 当输入为GPU上的张量时，模型将在同一GPU上计算结果

print(net(X))

# 确认模型参数存储在同一个GPU上

net[0].weight.data.device

tensor([[0.6505],
        [0.6505]], device='cuda:0', grad_fn=<AddmmBackward0>)


device(type='cuda', index=0)

: 